### ISSUE TITLE
Save and power down on battery level always power down, regardless of level set.

### ISSUE THREAD

**Issue by DDR0** [krontech/pychronos#28]
### Expected Behaviour
The camera should not power itself off until battery is at 5%.

### Actual Behaviour
The camera powers itself off when it is unplugged, regardless of the battery level.

-----

### Reproduction Prerequisites
One Chronos camera with a fully-charged battery and a network connection.

### Negative Reproduction
On the camera, run `gdbus call --system --dest ca.krontech.chronos.control --object-path /ca/krontech/chronos/control --method ca.krontech.chronos.control.set "{'saveAndPowerDownLowBatteryLevelPercent': <5>, 'saveAndPowerDownWhenLowBattery': <false> }"` and unplug the camera. Note how the camera stays powered on.

### Positive Reproduction
On the camera, run `gdbus call --system --dest ca.krontech.chronos.control --object-path /ca/krontech/chronos/control --method ca.krontech.chronos.control.set "{'saveAndPowerDownLowBatteryLevelPercent': <5>, 'saveAndPowerDownWhenLowBattery': <true> }"` and unplug the camera. Note how the camera powers itself off.

**Comment by oskirby** [comment]
Note that the camera has never had this feature implemented, the power-down behavior is controlled exclusively by the auto-power modes.

We have decided that the control API isn't really the one that's capable of knowing what to save when the battery becomes low and that we really want to move those decisions up to the GUI to decide. To aid in that, we think that the better approach is to add a parameter that notifies the GUI when the battery level becomes critical and let the GUI decide how to handle it.

To that effect, we propose to add the following properties:
  batteryCritical: boolean that indicates the camera power is critically low **and** that a shutdown is imminent (this should also be False whenever the AC adapter is present, regardless of battery charge).
  batteryThreshold: float [0, 1.0] charge level at which the battery considered critical and batteryCritical will change from false to true.
