### ISSUE TITLE
ioStatusSourceIo1, ioStatusSourceIo2, ioStatusSourceIo3 api values are undocumented

### ISSUE THREAD

**Issue by DDR0** [krontech/pychronos#32]
Expected Behaviour:
ctrl-f ioStatusSourceIo1 on https://github.com/krontech/pychronos should bring me to a relevant section of the readme.

Actual Behaviour:
No text is found, not even for ioStatusSourceIo.

**Comment by oskirby** [comment]
After some refactoring, these parameters have been grouped together into a single ioSourceStatus parameter which returns a dict of all the input signals to the IO block and their current values.
