### ISSUE TITLE
'delayTime' parameter cannot be set using 'ioMappingDelay' through cam-json

### ISSUE THREAD

**Issue by nfaliszewski** [krontech/pychronos#34]
The delay time of the io block can be set using 'ioDelayTime' and 'ioMapping', but it cannot be set by using 'ioMappingDelay'.

Example:
echo '{"ioMappingDelay": {"source":"toggle", "delayTime": 1.05, "debounce": 0, "invert": 0}}' | cam-json set -
returns this (notice that delayTime did not change:
{
   "ioMappingDelay": {
      "source": "toggle",
      "delayTime": 0,
      "debounce": 0,
      "invert": 0
   }
}

**Comment by oskirby** [comment]
After some refactoring, we switched it up so that the ioDelayTime is its own parameter now so that you can only configure it that way and setting ioMappingDelay has no effect on the configuration of ioDelayTime.
