### ISSUE TITLE
Save and Power Down on Low Power should be cancellable?

### ISSUE THREAD

**Issue by DDR0** [krontech/pychronos#41]
When the camera is about to save and power down, connected clients should be able to cancel the action. To do this, a new call and a new signal must be supplied; the call to cancel shut-down, and the signal to alert of pending shut-down.

Alternatively, see [CR14-114](<https://krontechnologies.atlassian.net/browse/CR14-114>) for the *other* fix to this, which is to poll the power level with the camApp and prompt to shut down there before shutting down.

**Comment by oskirby** [comment]
We expect this to be addressed as part of https://github.com/krontech/pychronos/issues/28 by changing the save-and-powerdown feature into a notification of critical charge state to give the GUI the decision on how to handle that.
